language: java

services:
  - mysql

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean verify

test:
  - mvn test -B

before_install:
  - mysql -u root --password="root"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS vsdb; '
  - mysql -e 'USE vsdb; create table  IF NOT EXISTS  Hospital (name varchar(255) not null, address varchar(255), phone varchar(255), primary key (name));'
  - mysql -e 'insert Hospital
              values
              ('Posadas', 'Avenida Presidente Arturo U. Illia s/n y Marconi Morón, B1684 El Palomar, Pcia de Buenos Aires', ''),
              ('Durand', 'Av. Díaz Vélez 5044, C1405DCS CABA', ''),
              ('Santojanni', 'Pilar 950, Buenos Aires', ''),
              ('Rivadavia', 'Av. Gral. Las Heras 2670, C1425ASQ CABA', '');
              commit; '


notifications:
  email:
    recipients:
      - gil.maricruz@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

