language: java

services:
  - mysql

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - cd VSAppBackEnd
  - mvn clean verify

test:
  - mvn test -B

before_install:
  - mysql -e 'CREATE DATABASE vsdb;'
  - mysql -e 'USE vsdb;'


notifications:
  email:
    recipients:
      - gil.maricruz@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

